# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 142b9b11740b71bbd2eacc037999a8195684e3a387cc45b08bd5c86b12846645575e751ad4b77ac78be26d82ddfcbf4b9239dc1ce2111cb491f1af3a588f34d8

test:
  secret_key_base: cc8d8f9d940b949cc89d38c5f5d89bd08cf32ac4c82b0724322dfee4d3aae3a9f54f81f4d1ca9264415278e1df2d4d6c6da771c827b86ff8d6ddaaf70d760039

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
